### PR TITLE
Fix #140: Add compile definitions for self-contained build

### LINKED ISSUE #140: Does not build without feature test macro set externally
**Describe the bug**
There's a build dependency here with `[cmake/sample_defs/mission_build_custom.cmake](https://github.com/nasa/cFE/blob/03166722cdde3f1b337742088e7137ebacf64734/cmake/sample_defs/mission_build_custom.cmake)`, which specifies a feature test macro. If a mission has a different and/or non-existent `mission_build_custom.cmake`, the compilation will fail for this target. It would be much better if the target specified its own requirements.

```cmake
# The _XOPEN_SOURCE directive is required for glibc to enable conformance with the
# the X/Open standard version 6, which includes POSIX.1c as well as SUSv2/UNIX98 extensions.
add_definitions(
    -D_XOPEN_SOURCE=600
)
```

**To Reproduce**
- Follow normal build instructions, but omit` mission_build_custom.cmake` from the `<mission>_defs` folder.

```
[ 50%] Building C object tools/elf2cfetbl/CMakeFiles/elf2cfetbl.dir/elf2cfetbl.c.o
make[4]: Leaving directory `build'
[ 50%] Built target cfe-build-env
inside get_version for core_api
tools/elf2cfetbl/elf2cfetbl.c:99:18: error: ‘PATH_MAX’ undeclared here (not in a function)
 char SrcFilename[PATH_MAX] = {""};
                  ^
tools/elf2cfetbl/elf2cfetbl.c: In function ‘OpenSrcFile’:
tools/elf2cfetbl/elf2cfetbl.c:1427:13: warning: implicit declaration of function ‘ctime_r’ [-Wimplicit-function-declaration]
             printf("Original Source File Modification Time: %s\n", ctime_r(&SrcFileStats.st_mtime, TimeBuff));
             ^
make[4]: *** [tools/elf2cfetbl/CMakeFiles/elf2cfetbl.dir/elf2cfetbl.c.o] Error 1
```

**Expected behavior**
The target builds successfully.

**System observed on:**
 - OS: CentOS 7
 - cFE/OSAL/PSP: draco-rc3 bundle

**Reporter Info**
Isaac Rowe, NASA JSC, Jacobs Technology

### PR DESCRIPTION
**Pull request by irowebbn**
**Describe the contribution**
A clear and concise description of what the contribution is.
- Fixes #140 

**Testing performed**
Steps taken to test the contribution:
1. `make distclean; make prep; make`

**Expected behavior changes**
A clear and concise description of how this contribution will change behavior and level of impact.
 - No behavior changes

**Contributor Info - All information REQUIRED for consideration of pull request**
Isaac Rowe, NASA JSC (Jacobs Technology)

### CODE REVIEW

**Comment by dzbaker** [comment]
30 November 2023: Closing as we are not targeting elf2cfetbl being runnable outside of cFE.

**Comment by irowebbn** [comment]
I don't understand this rationale. The purpose of this is not to make elf2cfetbl runnable outside of cFE, but to correctly declare dependencies.  `mission_build_custom.cmake` is marked as an _example_ file, but the `XOPEN_SOURCE` directive is _required_ for `elf2cfetbl` to compile correctly. If you want all the components to have it defined for them, then I guess it could go into `mission_build.cmake`, but ideally each CMake target should define its own requirements.

**Comment by dzbaker** [comment]
@irowebbn XOPEN_SOURCE isn't something that elf2cfetbl needs/uses, but rather something needed by the development environment/C library. These definitions are intended to go in mission_build_custom.cmake.

**Comment by irowebbn** [comment]
I'm sorry, but I still don't understand. elf2cfetbl uses `ctime_r`, which is only visible when setting the `XOPEN_SOURCE` feature test macro. 

Setting the macro in mission_custom_build.cmake is problematic for 2 reasons:
1.  The  `*_custom_*.cmake` files are meant to override default build behavior. But setting this feature test macro is necessary for the elf2cfetbl target to compile. Necessary build steps should be separated from configurable options. There's nothing indicating that some of the options in what cFE provides in sample_defs  should not be changed. This was the primary reason I submitted the patch.
2. This defines the macro for all the targets for local tools. Do all the targets need to have those symbols visible in order to compile? No, each target should be able to control the visibilities for themselves. Imagine I had a target that strictly followed the C standard but had conflicts with symbols brought in by the feature test macro. Probably a bad idea, but permitted nonetheless. I would have to use `target_remove_definitions` to undo what the mission_custom_build.cmake brought in.

**Pull request closed without merging**
