### PR TITLE
Fix #14, Add guide on creating table files

### LINKED ISSUE #14: Tutorial on using elf2cfetbl
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A guide on how to use elf2cfetbl to create an table file

**Describe alternatives you've considered**
none

**Additional context**
none

**Requester Info**
Anh Van, Nasa Goddard

### PR DESCRIPTION
**Pull request by avan989**
**Describe the contribution**
Fix #14, Add guide on creating table file using elf2cfetbl 

**Testing performed**
Steps taken to test the contribution:
1. Create a table file using elf2cfetbl

**Expected behavior changes**
No impact to behavior

**System(s) tested on:**
 - Hardware
 - OS: Ubuntu 18.04.03
 - elf2cfetbl version 3.0a

**Additional context**
None

**Contributor Info**
Anh Van, NASA Goddard

**Community contributors**
You must attach a signed CLA (required for acceptance) or reference one already submitted

### CODE REVIEW

**Comment by avan989** [comment]
Changed MyTblDefault to ${APPNAME}_default

**Comment by skliper** [comment]
> I suggest the search path behavior get outlined here, and take off the fsw/src in the 3.a. example if it's ignored anyways. Otherwise it implies a specific file, vs the search/override functionality.
> 
> So 2. could detail placing the application default table in the fsw/src directory, then note the build system search path for the file of this name - the mission *_defs directory first in case the mission needs to override the default followed by the application fsw/src directory.
> 
> Actually curious if it's more complicated than this, where you could prefix the file name with the platform and build different tables for different platforms?
> 
> @jphicky could you confirm? Is this general behavior already described somewhere that this file could refer to? (the whole search path, platform prefix business)

Turns out there isn't a search path.  This isn't applicable.

**Comment by jphickey** [comment]
I think this is OK now. 

But there _IS_ a search path for tables  - it is just using the basename only, rather than the full path of whatever is supplied in the command.  The sequence is as follows (where TBLWE==table basename without extension):

1. `${MISSION_DEFS}/tables/${TGT}_${TBLWE}.c`
2. `${MISSION_SOURCE_DIR}/tables/${TGT}_${TBLWE}.c`
3. `${MISSION_DEFS}/tables/${TBLWE}.c`
4. `${MISSION_SOURCE_DIR}/tables/${TBLWE}.c`
5. (passed-in relative path)

The supplied path does come into play, as the fallback at the end, if the search path fails to find anything matching within the mission-specific directories.

**Comment by skliper** [comment]
> I think this is OK now.
> 
> But there _IS_ a search path for tables - it is just using the basename only, rather than the full path of whatever is supplied in the command. The sequence is as follows (where TBLWE==table basename without extension):
> 
> 1. `${MISSION_DEFS}/tables/${TGT}_${TBLWE}.c`
> 2. `${MISSION_SOURCE_DIR}/tables/${TGT}_${TBLWE}.c`
> 3. `${MISSION_DEFS}/tables/${TBLWE}.c`
> 4. `${MISSION_SOURCE_DIR}/tables/${TBLWE}.c`
> 5. (passed-in relative path)
> 
> The supplied path does come into play, as the fallback at the end, if the search path fails to find anything matching within the mission-specific directories.

Got it, I suggest this get added to the guide.

**Comment by avan989** [comment]
added sequence for file table source

**Pull request merged**
